name: CMake Build (CI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Run tests
        run: ./build/RunTest

  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake

      - name: Configure CMake with clang
        run: cmake -B build-clang -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build with clang
        run: cmake --build build-clang --config ${{ env.BUILD_TYPE }}

      - name: Run tests (clang)
        run: ./build-clang/RunTest

  build-windows:
    runs-on: windows-latest
    env:
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

      - name: Configure CMake
        run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} -- /p:Platform=x64

      - name: Run tests
        run: .\build\Release\RunTest.exe
