name: CMake Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Установка зависимостей
        run: sudo apt update && sudo apt install -y cmake g++ git

      - name: Сборка с тестами
        run: |
          cmake -H. -B_build -DBUILD_TESTS=ON
          cmake --build _build

      - name: Запуск тестов
        run: |
          cmake --build _build --target test

